/**
 * This component displays detailed information about top 15 leaders
 * it will include elements like the leaders id, about, created , karma and submitted links
 * this component take in props related to the leader and render them
 * leader is the main page and /ingve is the route to display the details information about the leaders
 */

import React from 'react';
import { useParams } from 'react-router-dom';

// Define the Leader interface
interface Leader {
  id: string;
  about: string;
  created: number;
  karma: number;
  submitted: number[];
}

// information is manually retrieve from the url https://news.ycombinator.com/leaders
// user will navigate to a page that displays the following information below
const leaderData: { [key: string]: Leader } = {
  tptacek: {
    id: 'tptacek',
    about: `Having said thus much by way of introduction, I commit the following to the candour of the Publick.
    Helu! I'm Thomas.
    
    @tqbf@infosec.exchange
    thomas@sockpuppet.org
    thomas@fly.io`,
    created: 1173923448, // Date is updated to its Unix Timestamp
    karma: 394378,
    submitted: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  },
  ingve: {
    id: 'ingve',
    about: '',
    created: 1334188800,
    karma: 23456,
    submitted: [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
  },
  danso: {
    id: 'danso',
    about:
      'Amateur data scientist and photographer in Chicago.   Formerly: teaching at Stanford and programming+newsing at ProPublica  Blog: http://www.danwin.com   Twitter: https://twitter.com/dancow   [ my public key: https://keybase.io/dnguyen; my proof: https://keybase.io/dnguyen/sigs/69iS-DQno44YqjgaowUD_Zze660k3fojXZmHob-bgxA ]  ',
    created: 1308009600,
    karma: 34567,
    submitted: [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
  },
  pseudolus: {
    id: 'pseudolus',
    about: '	Unhappy moron',
    created: 1413936000,
    karma: 160015,
    submitted: [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
  },
  rbanffy: {
    id: 'rbanffy',
    about:
      'Seasoned software developer, proficient in Python, Java. Less proficient in Ruby and Lisp. A bit rusty in C and C++. Learning Erlang very slowly. Also a computer collector and restorer, lover of 8-bit computers, mainframes and interesting Unix workstations  email: username at that google mail thing   http://about.me/rbanffy    https://linkedin.com/in/ricardobanffy   [ my public key: https://keybase.io/rbanffy; my proof: https://keybase.io/rbanffy/sigs/HtF1uAf_RNpwIkNP1-YGWP_-3doWV6S5Cc1KywXeLYo ]       ',
    created: 1205280000,
    karma: 158755,
    submitted: [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
  },
  todsacerdoti: {
    id: 'todsacerdoti',
    about:
      '	Founder/CEO @ Pipedream.com. Also #girldad, investor & lifelong learner',
    created: 1579219200,
    karma: 158025,
    submitted: [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
  },
  tosh: {
    id: 'tosh',
    about:
      '	https://chesscatsapp.com (a fun way to play chess)  https://moreepisodes.com (tv show episodes generated by GPT-4) https://jamshelf.com (open source Clubhouse)  https://magic.do (early stage fund)  https://lemmings.io (sci-fi themed hackathons (think "zombie apocalypse", "aliens"))  https://applesilicongames.com (game compatibility and game performance on Apple Silicon Macs) https://devmonthly.com (curated news & input & jobs for software engineers)  https://blossom.io (project tracking for distributed teams)  more from me around the web:  https://twitter.com/__tosh     https://github.com/tosh https://angel.co/tosh  https://medium.com/@__tosh https://lobste.rs/u/tosh https://dribbble.com/tosh https://linkedin.com/in/tschranz https://instagram.com/thomas.schranz https://facebook.com/thomas.schranz  {UX Service Game} Design, Typography, Clojure, Lisp, Python, Tea, Minimalism, Dao,  my public key: https://keybase.io/tosh; my proof: https://keybase.io/tosh/sigs/gBG56O339IbBPh1iaudGL3dgJuX2yONIATYv62xHXdg ]    ',
    created: 1272931200,
    karma: 156321,
    submitted: [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
  },
  Tomte: {
    id: 'Tomte',
    about:
      '	[ my public key: https://keybase.io/2uo; my proof: https://keybase.io/2uo/sigs/3Nc5FGsaD-8qFEmS8FvyXv9aA3sAS6hx29MBPq8g6EA ]',
    created: 1345680000,
    karma: 149901,
    submitted: [71, 72, 73, 74, 75, 76, 77, 78, 79, 80],
  },
  JumpCrisscross: {
    id: 'JumpCrisscross',
    about:
      'Trade private equity. Former aerospace investment banker, and before that, algorithmic equity derivatives trader. FinTech + Space + B2C angel & seed investor. Jackson Hole local; frequently in New York and the Bay Area',
    created: 1306800000,
    karma: 145410,
    submitted: [81, 82, 83, 84, 85, 86, 87, 88, 89, 90],
  },
  Animats: {
    id: 'Animats',
    about: 'John Nagle',
    created: 1410134400,
    karma: 143342,
    submitted: [91, 92, 93, 94, 95, 96, 97, 98, 99, 100],
  },
  lxm: {
    id: 'lxm',
    about: '	Engineer in Southern California',
    created: 1173923456,
    karma: 138876,
    submitted: [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
  },
  patio11: {
    id: 'patio11',
    about: `Howdy. I'm Patrick. I work for the Internet. Previously: Stripe, Starfighter, Appointment Reminder, Bingo Card Creator.
blog: https://www.kalzumeus.com

My best email is patrick@ the blog domain. Open invitation: if you're reading this, I'm happy to receive email about any software/startup/etc topic from you at any time. I generally reply to about 60% of unsolicited email from HNers, and if I don't reply to you, it is only because I got busy, not because of anything you said.

I write a lot. Most of what I write here is unless otherwise stated in my personal capacity, and opinions expressed may not be shared by employers, clients, friends, etc.`,
    created: 1226880000,
    karma: 127522,
    submitted: [111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
  },
  ColinWright: {
    id: 'ColinWright',
    about: `If you want to contact me, find me on the web. I am especially interested in math, juggling, programming, and education, and since there are other people with my name you'll probably need to include at least one of those terms in any search.
    I was once a prolific contributor and commenter, but no more. I go through bouts of submitting stuff, but then go and disappear for lengths of time. If there is something you'd like me to see or comment on, you can email me. Don't ask me to upvote things. If it is interesting (to me) then I will.
    
    Submissions do not imply endorsement.
    
    To contact me about the idea of spaced repetition by email experiment, use this address:
    
        SR_Expt@solipsys.co.uk
    My spam filtering is pretty severe, but I've put the word "Dysprosium" on the allow-list - quote that and your email will get through.
    (Note: That email address has been harvested, and is now receiving invitations to blogs, etc. If you want to get in touch, quoting the element name is needed)
    
    I used to have an email here but it got harvested by spammers - I'm looking at you, mbientlab.com - so it has been removed. This is a temporary one:
    
    HN_a7dab854@solipsys.co.uk
    
    Update: That email address has been harvested and is now being spammed. Emails sent to it will result in the sender being blocked. To send me email, add one to the username. That will get you automatically on the allow-listed.`,
    created: 1260748800,
    karma: 127473,
    submitted: [121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
  },
  rayiner: {
    id: 'rayiner',
    about: '',
    created: 1293571200,
    karma: 121489,
    submitted: [131, 132, 133, 134, 135, 136, 137, 138, 139, 140],
  },
  dragonwriter: {
    id: 'dragonwriter',
    about: '',
    created: 1352937600,
    karma: 118265,
    submitted: [141, 142, 143, 144, 145, 146, 147, 148, 149, 150],
  },
};

const LeaderDetail: React.FC = () => {
  const { id } = useParams<{ id: string }>();

  if (!id) {
    return <div>Error: No ID provided</div>;
  }

  const leader = leaderData[id];

  if (!leader) {
    return <div>Leader not found</div>;
  }

  const formattedDate = new Date(leader.created * 1000).toLocaleString();

  return (
    <div className="container mx-auto p-4">
      <h1 className="text-2xl font-bold mb-4">Leader Details</h1>
      <p>
        <strong>About:</strong> {leader.about}
      </p>
      <p>
        <strong>Created:</strong> {formattedDate}
      </p>
      <p>
        <strong>Id:</strong> {leader.id}
      </p>
      <p>
        <strong>Karma:</strong> {leader.karma}
      </p>
      <p>
        <strong>Submitted:</strong>
      </p>
      <ul>
        {leader.submitted.slice(0, 5).map((id) => (
          <li key={id}>
            <a
              href={`https://hacker-news.firebaseio.com/v0/item/${id}.json?print=pretty`}
              target="_blank"
              rel="noopener noreferrer"
              className="text-blue-500 hover:underline"
            >
              {`https://hacker-news.firebaseio.com/v0/item/${id}.json?print=pretty`}
            </a>
          </li>
        ))}
      </ul>
    </div>
  );
};

export default LeaderDetail;
